#!/bin/sh
#
# Run test suite for immut

set -e


if command -v yarn > /dev/null; then
    yarn -s yarns/immut.shell-lib yarns/*.yarn
else
    echo "WARNING: 'yarn' scenario test tool (part of 'cmdtest' " \
	 "package) was not found." >&2
    exit 1
fi
