#!/bin/sh
#
# Run test suite for immut
# This script assumes that the ip of the services are passed
# through parameters

# usage: ./check <haproxy ip> <gitserver ip>

set -e

haproxy_ip="$1"
gitserver_ip="$2"

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

. $SCRIPTPATH/immut.shell-lib


if [ "x$TMPDIR" == "x" ]; then
    TMPDIR="/tmp"
    mkdir -p /sysroot/tmp
fi

TMPDIR="$TMPDIR/testSuite"

mkdir -p "$TMPDIR"
TMPDIR=$(mktemp -d -p "$TMPDIR")
export TMPDIR

if command -v yarn > /dev/null; then
    yarn --tempdir "$TMPDIR" --snapshot \
         --env "gitserver_ip=$gitserver_ip" \
         --env "haproxy_ip=$haproxy_ip" \
         -s "$SCRIPTPATH"/immut.shell-lib \
         "$SCRIPTPATH"/yarns/*.yarn
else
    echo "ERROR: "yarn" binary not found!!"
fi
